const actors=['Adriana García','Alejandra Herreros','Alex Grau','Alex Robles','Ana Sanchez','Angela Grau','Antonio Leonato','Carla Alonso','Catalina De La Mano','Clara Sanchez','Claudia Leonato','Cristian Lopez','Daniela Marcos','Daniella Rivero','Dario Marcos','Helia','Irene Garcia','Iría Ruiz','Jimena Gonzalez','Jonathan Grau','Lucas Marcos','Marco Augusto Alija','Mencia De La Mano','Neizan Rey','Nerea Gonzalez','Nerea Rey','Nerea Ruiz ','Nico Ballesteros','Samuel Sobejano','Santiago Calvo','Sergio Calvo']
const locations=['Azadinos','Carbajal','Cuadros','Lorenzana','Pobladura','Santibáñez','Sariegos']
const levels=['1º Inf','2º Inf','3º Inf','1º Prim','2º Prim','3º Prim','4º Prim','5º Prim','6º Prim']
const genres=['Baile','Comedia','Deporte','Musical']
const videoIds=['1wtx7VW4A5TK5iJU0j-pM7OsYgHk9Aqyo','1Us6KZNksR7ShQMzJrm82HDwMyX5HNa29','10MrLHQteaU-vcQkxn7Gsj8jbyPd6QajT','1zdhfCYjOprHo7cHDLVc0YRE_L0w7lnXG','1qfQStcMCxsGnpEifOiD1ZVcMKsBe9P-M','14laNx97Kw-dQDJnJ9MKK8wKYRQ4EuH6W','1xEw7Py00pN6yoTp0HOyxq4ekiJq-Uot6','1LeiHgARMYRZww0bqWWdkXnDqfyeHwwC1','1qAoP7IGWXXkLaWt23EZMm2QQCjC5w2Ln','1s4Ml55S2GWE6-MdreacZ8tlT-QssFz35','1EuD0TdvMpMY5zD7WLRU78ovmXL3w8yoL','1kCGmCPZFWcUcaOjYi4qZV2ENy2kX1EmK','1uZwSxq9D4pdzFmzdfct1iz-z9l4D0kek','1bCrNu2tkBa-pkzV9P8FwOCGG2OI8SnWH','1TOQ7tOUAoXA4pGKPjbp7Zv5P-rM69Zvm','1Psje4C5SFuYTMRethyuIBvSI1zuqEI8u','1R5qevJBXAvJwIdCQjAWYGryFVELF85i0','1DlgDBm_F6ojz1avwMmOKsVnjm06vHIl_','1x0rUUV3OlFAgZT-1MzXSQJ1VAGiXUpo0','1xsGilWrE9AnqRbTVE_sQr20IJh6QNwzc','11TrfK7I5GEyya5LxUK9LB0phpO7z0Ofp','1MyCMLjUKS4c6MB5IvGlr5z12bxmvs_bz','1ToC6h0CdUgpNESDPwGNeMvjTM4oeYFhs','1KO5yYwhgpEDlEI3rKT1PcCAfGSe0IaUM','1bF-9bnNnA2GROYhkIHtzZ1-WRffJ0B1b','1BFp5uazAlnW_uBWt6dqWTfix4oyrtdpT','1ksqTluweSzVD-zvfr4s7rm4pF4zfjqJF','1eHGwLxc2djSIFXwpPvLvOmbLDa3a7tJq']
const db=[[[0],[3,6],[8,22],[6],0],[[0],[3,6],[18,24],[3],1],[[0],[1],[29],[3],2],[[0],[4],[6],[3],3],[[0],[2,5],[4,9],[3],4],[[0],[6],[16],[1],5],[[0],[7],[10],[3],6],[[0],[8],[7],[4],7],[[1],[3],[13],[6],8],[[1],[3],[13],[6],9],[[1],[3],[23],[3],10],[[1],[1],[21],[3],11],[[1],[4],[20],[3],12],[[1],[4],[30],[3],13],[[1],[5],[9],[3],14],[[1],[5],[15],[3],15],[[1],[5],[26],[6],16],[[1],[5],[27],[3],17],[[1],[5],[25],[3],18],[[1],[6],[12],[0],19],[[1],[6],[14],[3],20],[[1],[6],[28],[3],21],[[1],[7],[17],[6],22],[[2],[4],[0],[3],23],[[2],[5],[1],[3],24],[[2],[5,7,8],[11,5,2,19],[4],25],[[2],[8],[3],[6],26],[[2],[8],[7],[4],27]]
const videoHostUrl='https://drive.google.com/'
const videoSourceUrlPrefix=videoHostUrl+'uc?export=download&id='
const videoFrameUrlPrefix=videoHostUrl+'file/d/'
const videoFrameUrlSuffix='/preview?autoplay=1'
const locationSelect=document.getElementById('location');const searchInput=document.getElementById('search');const levelSelect=document.getElementById('level');const genreSelect=document.getElementById('genre');const resultBody=document.getElementById('result');function populateSelectOptions(selectElement,options){options.forEach((item,index)=>selectElement.options[selectElement.options.length]=new Option(item,index.toString()));}
function disableEmptyOptions(selectElement,filterFunctionArgumentPosition){const options=selectElement.options;const filterArguments=['-1','-1','-1'];let optionValue;for(let i=1;i<options.length;++i){optionValue=options[i].value;filterArguments[filterFunctionArgumentPosition]=optionValue;const filteredDb=db.filter(entry=>isIncluded(entry,'',...filterArguments));if(filteredDb.length===0)options[i].disabled=true;}}
function disableAllEmptyOptions(){[locationSelect,levelSelect,genreSelect].forEach((e,i)=>disableEmptyOptions(e,i));}
function createTableBodyRow(genreIndexes,levelIndexes,actorIndexes,locationIndexes,videoId){const tr=document.createElement('tr');[locationIndexes.map(i=>locations[i]).join(', '),levelIndexes.map(i=>levels[i]).join(', '),genreIndexes.map(i=>genres[i]).join(', '),actorIndexes.map(i=>actors[i]).join(', ')].forEach(text=>tr.insertCell().appendChild(document.createTextNode(text)));tr.setAttribute('data',videoIds[videoId]);return tr;}
function isIncluded(dbEntry,actorSubstr,locationIndex,levelIndex,genreIndex){let genreIndexes,levelIndexes,actorIndexes,locationIndexes;[genreIndexes,levelIndexes,actorIndexes,locationIndexes]=dbEntry;if(levelIndex!=='-1'&&!levelIndexes.includes(Number(levelIndex)))return false;if(genreIndex!=='-1'&&!genreIndexes.includes(Number(genreIndex)))return false;if(locationIndex!=='-1'&&!locationIndexes.includes(Number(locationIndex)))return false;if(actorSubstr!==''&&!actorIndexes.map(i=>actors[i]).join('').toLocaleLowerCase().includes(actorSubstr.toLocaleLowerCase()))return false;return true;}
function clearResultTableBody(){while(resultBody.firstChild){resultBody.removeChild(resultBody.firstChild);}}
function evaluateResults(){const locationIndex=locationSelect.options[locationSelect.selectedIndex].value;const levelIndex=levelSelect.options[levelSelect.selectedIndex].value;const genreIndex=genreSelect.options[genreSelect.selectedIndex].value;const actorSubstr=searchInput.value;const filteredDb=db.filter(entry=>isIncluded(entry,actorSubstr,locationIndex,levelIndex,genreIndex));clearResultTableBody();filteredDb.forEach(entry=>resultBody.appendChild(createTableBodyRow(...entry)));}
function errorLoadingVideo(bigPicture){BigPicture({el:bigPicture.el,iframeSrc:videoFrameUrlPrefix+bigPicture.vidSrc.substring(videoSourceUrlPrefix.length)+videoFrameUrlSuffix,onError:function(){alert('Problemas a cargar el video');}})}
function onResultClick(event){const tr=event.target.closest('tr');const videoId=tr.getAttribute('data');BigPicture({el:tr,vidSrc:videoSourceUrlPrefix+videoId,onError:errorLoadingVideo})}
[[locationSelect,locations],[levelSelect,levels],[genreSelect,genres]].forEach(pair=>populateSelectOptions(pair[0],pair[1]));disableAllEmptyOptions();[searchInput,locationSelect,levelSelect,genreSelect].forEach(element=>element.addEventListener('change',evaluateResults));resultBody.addEventListener('click',onResultClick);evaluateResults();